apiVersion: v1
kind: ConfigMap
metadata:
  name: contacts-gateway-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  codeAll: ""
  codeById: ""
  ApiContactsUrl: contacts-queue-service
  PORT: "80"