# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: contacts-gateway-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  codeAll: ""
  codeById: ""
  ApiContactsUrl: contacts-queue-service
  PORT: "80"
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-gateway-deployment
  labels:
    app: contacts-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-gateway
  template:
    metadata:
      labels:
        app: contacts-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: contacts-gateway
          image: gugol94/fiapcontacts-apigateway
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: contacts-gateway-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "90m"
            limits:
              memory: "256Mi"
              cpu: "100m"
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: contacts-gateway-service
  labels:
    app: contacts-gateway
spec:
  type: NodePort
  selector:
    app: contacts-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
