apiVersion: v1
kind: Service
metadata:
  name: contacts-gateway-service
  labels:
    app: contacts-gateway
spec:
  type: NodePort
  selector:
    app: contacts-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
